Repository mindspore-lab/mindyolo, pull requests merged in 2023-09, with the labels that each got.

#196 Add YOLOv8x Segmentation
  MODEL_ZOO.md
  configs/yolov8/README.md
  configs/yolov8/seg/hyp.scratch.high.seg.yaml
  configs/yolov8/seg/yolov8-seg-base.yaml
  configs/yolov8/seg/yolov8x-seg.yaml
  demo/predict.py
  deploy/predict.py
  deploy/test.py
  mindyolo/data/albumentations.py
  mindyolo/data/copypaste.py
  mindyolo/data/dataset.py
  mindyolo/data/loader.py
  mindyolo/data/perspective.py
  mindyolo/data/utils.py
  mindyolo/models/heads/__init__.py
  mindyolo/models/heads/yolov8_head.py
  mindyolo/models/losses/label_assignment.py
  mindyolo/models/losses/yolov8_loss.py
  mindyolo/models/model_factory.py
  mindyolo/models/yolov3.py
  mindyolo/models/yolov4.py
  mindyolo/models/yolov5.py
  mindyolo/models/yolov7.py
  mindyolo/models/yolov8.py
  mindyolo/models/yolox.py
  mindyolo/utils/callback.py
  mindyolo/utils/metrics.py
  mindyolo/utils/poly.py
  mindyolo/utils/train_step_factory.py
  mindyolo/utils/trainer_factory.py
  mindyolo/utils/utils.py
  mindyolo/version.py
  test.py
  tests/dataset_plots.py
  tests/modules/test_create_loader.py
  tests/modules/test_create_trainer.py
  train.py
Labels: rfc

#197 fix yolov8x-seg bug
  README.md
  configs/yolov8/seg/yolov8-seg-base.yaml
  configs/yolov8/seg/yolov8x-seg.yaml
  deploy/test.py
  mindyolo/data/albumentations.py
  mindyolo/data/dataset.py
  mindyolo/utils/trainer_factory.py
  mindyolo/utils/utils.py
  test.py
  tests/modules/test_create_trainer.py
  train.py
Labels: bug

#200 Detection task adapt new data processing
  GETTING_STARTED.md
  configs/yolov3/hyp.scratch.yaml
  configs/yolov4/hyp.scratch.yaml
  configs/yolov5/hyp.scratch-high.yaml
  configs/yolov5/hyp.scratch-low.yaml
  configs/yolov7/hyp.scratch.p5.yaml
  configs/yolov7/hyp.scratch.p6.yaml
  configs/yolov7/hyp.scratch.tiny.yaml
  configs/yolov8/hyp.scratch.high.yaml
  configs/yolov8/hyp.scratch.low.yaml
  configs/yolov8/hyp.scratch.med.yaml
  configs/yolox/hyp.scratch.yaml
  mindyolo/data/dataset.py
  mindyolo/data/utils.py
Labels: bug, rfc

#205 Modify simple use cases in model definition
  mindyolo/models/heads/yolov5_head.py
  mindyolo/models/yolov3.py
  mindyolo/models/yolov4.py
  mindyolo/models/yolov5.py
  mindyolo/models/yolov7.py
  mindyolo/models/yolov8.py
  mindyolo/models/yolox.py
Labels: bug, rfc

#208 fix detection label visualization
  mindyolo/utils/poly.py
  tests/dataset_plots.py
Labels: bug, rfc

#209 fix yolov8-seg non-overlap data format bug
  mindyolo/data/utils.py
Labels: bug

#215 fix data.utils.segment2box bug
  mindyolo/data/utils.py
Labels: bug
