Repository mindspore-lab/mindyolo, pull requests merged in 2023-08, with the labels that each got.

#180 add deploy predict test
  deploy/__init__.py
  tests/modules/test_deploy_predict.py
Labels: inside-test

#183 amend mkdocs's verison
  docs/en/tutorials/modelarts.md
  docs/zh/tutorials/modelarts.md
  requirements/docs.txt
Labels: bug

#184 modify finetune tutorial
  demo/predict.py
  docs/zh/how_to_guides/data_preparation.md
  examples/finetune_SHWD/README.md
  examples/finetune_SHWD/convert_yolov7-tiny_pretrain_ckpt.py
  examples/finetune_SHWD/finetune_shwd.py
  examples/finetune_SHWD/yolov7-tiny_shwd.yaml
  requirements/cpu_requirements.txt
Labels: documentation, inside-test, rfc

#189 fix yolov4 EvalWhileTrain bug
  mindyolo/models/heads/yolov4_head.py
Labels: bug, inside-test

#193 fix a typo & and a note
  deploy/README.md
Labels: documentation
