Repository mindspore-lab/mindyolo, pull requests merged in 2023-05, with the labels that each got.

#74 fix is export and update readme
  deploy/GETTING_STARTED.md
  deploy/predict.py
  deploy/test.py
  mindyolo/models/heads/yolov5_head.py
Labels: bug, documentation, inside-test

#76 update mindx requirements
  deploy/README.md
Labels: documentation, inside-test

#79 Add yolov8 model
  GETTING_STARTED.md
  MODEL_ZOO.md
  README.md
  configs/yolov8/README.md
  configs/yolov8/hyp.scratch.nano.yaml
  configs/yolov8/yolov8n.yaml
  demo/predict.py
  deploy/predict.py
  deploy/test.py
  mindyolo/models/losses/yolov8_loss.py
  mindyolo/models/model_factory.py
  mindyolo/models/yolov8.py
  mindyolo/utils/metrics.py
  mindyolo/utils/trainer_factory.py
  test.py
  tests/dataset_plots.py
  train.py
Labels: inside-test, rfc

#80 fix model_zoo.md
  MODEL_ZOO.md
Labels: inside-test, rfc

#81 fix Supported Algorithms in README.md
  README.md
Labels: documentation, inside-test, rfc

#82 add yolov4 for init file and model_factory
  mindyolo/models/__init__.py
  mindyolo/models/model_factory.py
Labels: inside-test, rfc

#83 fix meshgrid bug in depoly.
  mindyolo/models/heads/yolov3_head.py
  mindyolo/models/heads/yolov5_head.py
  mindyolo/models/heads/yolov7_head.py
  mindyolo/models/heads/yolov8_head.py
  mindyolo/models/layers/utils.py
Labels: bug, inside-test

#85 Model parsing adding key-value pairing method configuration parameters
  mindyolo/models/model_factory.py
  mindyolo/optim/group_params.py
Labels: inside-test, rfc

#87 update deploy yolov4 & v8n
  deploy/GETTING_STARTED.md
  deploy/README.md
Labels: documentation, inside-test, rfc

#90 add yolox model
  MODEL_ZOO.md
  README.md
  configs/yolox/hyp.scratch.yaml
  configs/yolox/yolox-darknet53-2nd.yaml
  configs/yolox/yolox-darknet53.yaml
  configs/yolox/yolox-l-2nd.yaml
  configs/yolox/yolox-l.yaml
  configs/yolox/yolox-m-2nd.yaml
  configs/yolox/yolox-m.yaml
  configs/yolox/yolox-nano-2nd.yaml
  configs/yolox/yolox-nano.yaml
  configs/yolox/yolox-s-2nd.yaml
  configs/yolox/yolox-s.yaml
  configs/yolox/yolox-tiny-2nd.yaml
  configs/yolox/yolox-tiny.yaml
  configs/yolox/yolox-x-2nd.yaml
  configs/yolox/yolox-x.yaml
  mindyolo/data/dataset.py
  mindyolo/models/__init__.py
  mindyolo/models/heads/__init__.py
  mindyolo/models/heads/yolox_head.py
  mindyolo/models/layers/__init__.py
  mindyolo/models/layers/bottleneck.py
  mindyolo/models/layers/conv.py
  mindyolo/models/layers/spp.py
  mindyolo/models/layers/utils.py
  mindyolo/models/losses/__init__.py
  mindyolo/models/losses/iou_loss.py
  mindyolo/models/losses/yolox_loss.py
  mindyolo/models/model_factory.py
  mindyolo/models/yolox.py
  mindyolo/optim/optim_factory.py
  mindyolo/optim/scheduler.py
  mindyolo/utils/config.py
  mindyolo/utils/trainer_factory.py
  train.py
Labels: bug, inside-test, rfc

#93 add yolov4(mish-leakyrelu) yaml and weight
  MODEL_ZOO.md
  configs/yolov4/README.md
  configs/yolov4/yolov4.yaml
Labels: inside-test, rfc

#89 revise GETTING_STARTED.md
  GETTING_STARTED.md
Labels: documentation, inside-test, rfc

#95 add s and m scale to yolox
  MODEL_ZOO.md
  configs/yolox/README.md
  configs/yolox/yolox-m-2nd.yaml
Labels: documentation, inside-test, rfc

#96 Add GettingStart.md Chinese version
  GETTING_STARTED_CN.md
Labels: documentation, inside-test, rfc

#98 fix bug of config log
  mindyolo/utils/config.py
  train.py
Labels: bug, inside-test

#101 add yolox-n weight
  MODEL_ZOO.md
  configs/yolox/README.md
  configs/yolox/yolox-darknet53-2nd.yaml
  configs/yolox/yolox-l-2nd.yaml
  configs/yolox/yolox-nano-2nd.yaml
  configs/yolox/yolox-s-2nd.yaml
  configs/yolox/yolox-tiny-2nd.yaml
  configs/yolox/yolox-x-2nd.yaml
Labels: documentation, rfc

#103 Add yolov8-s/m/l weight and modify some docs
  GETTING_STARTED.md
  GETTING_STARTED_CN.md
  MODEL_ZOO.md
  configs/yolov3/README.md
  configs/yolov4/README.md
  configs/yolov5/README.md
  configs/yolov7/README.md
  configs/yolov8/README.md
  configs/yolox/README.md
  mindyolo/models/losses/iou_loss.py
  mindyolo/models/losses/yolov7_loss.py
  mindyolo/utils/metrics.py
Labels: documentation, inside-test, rfc

#100 Add README.md Chinese version
  README.md
  README_CN.md
Labels: documentation, inside-test, rfc

#104 remove a useless colon
  GETTING_STARTED.md
Labels: documentation, inside-test

#110 update yolov8&yolov4 deploy weight
  deploy/README.md
Labels: documentation, rfc

#108 add tutorials/modelarts_CN.md
  GETTING_STARTED_CN.md
  train.py
  tutorials/modelarts_CN.md
Labels: documentation, inside-test, rfc

#113 simplify yolov4 yaml;revise Residualblock
  configs/yolov4/yolov4.yaml
  mindyolo/models/layers/bottleneck.py
Labels: bug, inside-test, rfc

#116 fix a yolov7 bug
  mindyolo/models/yolov7.py
Labels: bug

#118 fix deploy README from weight to ckpt
  deploy/README.md
Labels: bug, documentation

#121 add yolox l,x,darknet53 weight
  MODEL_ZOO.md
  configs/yolox/README.md
Labels: documentation, inside-test, rfc

#119 Add modelart tutorial EN version and revise CN version
  tutorials/modelarts.md
  tutorials/modelarts_CN.md
Labels: documentation, inside-test
