Repository mindspore-lab/mindyolo, pull requests merged in 2023-06, with the labels that each got.

#123 add training hook and apply it on yolox
  configs/yolox/README.md
  configs/yolox/hyp.scratch.yaml
  configs/yolox/yolox-darknet53-2nd.yaml
  configs/yolox/yolox-l-2nd.yaml
  configs/yolox/yolox-m-2nd.yaml
  configs/yolox/yolox-nano-2nd.yaml
  configs/yolox/yolox-nano.yaml
  configs/yolox/yolox-s-2nd.yaml
  configs/yolox/yolox-s.yaml
  configs/yolox/yolox-tiny-2nd.yaml
  configs/yolox/yolox-tiny.yaml
  configs/yolox/yolox-x-2nd.yaml
  mindyolo/optim/scheduler.py
  mindyolo/utils/callback.py
  mindyolo/utils/logger.py
  mindyolo/utils/registry.py
  mindyolo/utils/trainer_factory.py
  mindyolo/utils/utils.py
  train.py
Labels: inside-test, rfc

#126 add hook for training process
  configs/yolox/README.md
  configs/yolox/hyp.scratch.yaml
  configs/yolox/yolox-darknet53-2nd.yaml
  configs/yolox/yolox-l-2nd.yaml
  configs/yolox/yolox-m-2nd.yaml
  configs/yolox/yolox-nano-2nd.yaml
  configs/yolox/yolox-nano.yaml
  configs/yolox/yolox-s-2nd.yaml
  configs/yolox/yolox-s.yaml
  configs/yolox/yolox-tiny-2nd.yaml
  configs/yolox/yolox-tiny.yaml
  configs/yolox/yolox-x-2nd.yaml
  mindyolo/optim/scheduler.py
  mindyolo/utils/callback.py
  mindyolo/utils/logger.py
  mindyolo/utils/registry.py
  mindyolo/utils/trainer_factory.py
  mindyolo/utils/utils.py
  train.py
Labels: inside-test, rfc

#127 Adapt to MindSpore2.0
  configs/yolov8/hyp.scratch.high.yaml
  configs/yolov8/hyp.scratch.low.yaml
  configs/yolov8/hyp.scratch.med.yaml
  configs/yolov8/yolov8-base.yaml
  mindyolo/data/loader.py
  mindyolo/models/heads/yolov3_head.py
  mindyolo/models/heads/yolov5_head.py
  mindyolo/models/heads/yolov7_head.py
  mindyolo/models/heads/yolov8_head.py
  mindyolo/models/heads/yolox_head.py
  mindyolo/models/layers/bottleneck.py
  mindyolo/models/layers/utils.py
  mindyolo/models/losses/iou_loss.py
  mindyolo/models/losses/yolov3_loss.py
  mindyolo/models/losses/yolov4_loss.py
  mindyolo/models/losses/yolov5_loss.py
  mindyolo/models/losses/yolov7_loss.py
  mindyolo/models/losses/yolov8_loss.py
  mindyolo/models/losses/yolox_loss.py
  mindyolo/optim/ema.py
  mindyolo/utils/train_step_factory.py
  mindyolo/utils/trainer_factory.py
  mindyolo/utils/utils.py
  train.py
Labels: inside-test, rfc

#129 show path of registry modules
  mindyolo/utils/callback.py
  mindyolo/utils/registry.py
  mindyolo/utils/trainer_factory.py
Labels: inside-test, rfc

#124 add finetune tutorial
  GETTING_STARTED.md
  GETTING_STARTED_CN.md
  examples/finetune_SHWD/README.md
  examples/finetune_SHWD/convert_shwd2yolo.py
  examples/finetune_SHWD/convert_yolov7-tiny_pretrain_ckpt.py
  examples/finetune_SHWD/finetune_shwd.py
  examples/finetune_SHWD/yolov7-tiny_shwd.yaml
  mindyolo/utils/config.py
  train.py
  tutorials/custom_dataset.md
Labels: documentation, inside-test, rfc

#138 update readme algin with deploy lite 2.0
  deploy/GETTING_STARTED.md
  deploy/MINDX.md
  deploy/README.md
  deploy/reqirements.txt
Labels: documentation

#136 add modules test
  examples/finetune_SHWD/README.md
  examples/finetune_SHWD/finetune_shwd.py
  examples/finetune_SHWD/yolov7-tiny_shwd.yaml
  tests/README.md
  tests/modules/test_create_group_param.py
  tests/modules/test_create_loss.py
  tests/modules/test_create_model.py
  tests/modules/test_create_optimizer.py
  tests/modules/test_create_trainer.py
Labels: inside-test, rfc

#146 update README
  README.md
  README_CN.md
  RELEASE.md
  mindyolo/utils/trainer_factory.py
  train.py
Labels: documentation

#148 fix mindyolo/version.py to r0.1
  mindyolo/version.py
Labels: bug, documentation, inside-test

#141 add configuration.md
  train.py
  tutorials/configuration_CN.md
Labels: documentation, inside-test, rfc

#150 add mkdocs files
  docs/en/how_to_guides/write_a_new_model.md
  docs/en/index.md
  docs/en/modelzoo.md
  docs/en/notes/changelog.md
  docs/en/notes/code_of_conduct.md
  docs/en/notes/contributing.md
  docs/en/notes/faq.md
  docs/en/readme.md
  docs/en/reference/data.md
  docs/en/reference/loss.md
  docs/en/tutorials/configuration.md
  docs/en/tutorials/deployment.md
  docs/en/tutorials/finetune.md
  docs/en/tutorials/modelarts.md
  docs/en/tutorials/quick_start.md
  docs/en/tutorials/readme.md
  docs/gen_ref_pages.py
  docs/zh/how_to_guides/write_a_new_model.md
  docs/zh/index.md
  docs/zh/modelzoo.md
  docs/zh/notes/changelog.md
  docs/zh/notes/code_of_conduct.md
  docs/zh/notes/contributing.md
  docs/zh/notes/faq.md
  docs/zh/reference/data.md
  docs/zh/reference/loss.md
  docs/zh/tutorials/configuration.md
  docs/zh/tutorials/deployment.md
  docs/zh/tutorials/finetune.md
  docs/zh/tutorials/modelarts.md
  docs/zh/tutorials/quick_start.md
  docs/zh_cn/readme.md
  docs/zh_cn/tutorials/readme.md
  mkdocs.yml
Labels: documentation

#149 Add .github/workflows/docs.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  mindyolo/version.py
  requirements/docs.txt
Labels: documentation

#143 support online & ofline distributed inference
  mindyolo/utils/callback.py
  mindyolo/utils/logger.py
  mindyolo/utils/trainer_factory.py
  mindyolo/utils/utils.py
  test.py
  train.py
Labels: inside-test, rfc

#152 update huaweiyun tutorial
  tutorials/cloud/modelarts_CN.md
  tutorials/cloud/openi.md
  tutorials/cloud/openi_CN.md
Labels: documentation, rfc

#153 amend the link of a pic
  README.md
  README_CN.md
  mkdocs.yml
Labels: bug, documentation

#156 [Bugfix] Fix datasink mode accuracy zero bug
  .github/workflows/docs.yml
  examples/finetune_SHWD/finetune_shwd.py
  mindyolo/utils/all_finite.py
  mindyolo/utils/callback.py
  mindyolo/utils/train_step_factory.py
  mindyolo/utils/trainer_factory.py
  train.py
Labels: bug, inside-test

#160 enable test cases
  .github/workflows/ci.yml
  requirements/cpu_requirements.txt
  tests/modules/test_create_trainer.py
Labels: inside-test, rfc
